CREATE TABLE CHEAP_MEALS AS SELECT * FROM INGREDIENT WHERE price < 15;
CREATE TABLE VEGAN_INGREDIENT AS SELECT * FROM INGREDIENT WHERE FALSE;

INSERT INTO VEGAN_INGREDIENT SELECT * FROM INGREDIENT WHERE vegan = true;
CREATE VIEW EXPENSIVE_MEAL AS SELECT * FROM INGREDIENT WHERE price > 15;

CREATE VIEW LACTOSE_FREE_INGREDIENT AS SELECT * FROM INGREDIENT WHERE contains_lactose = false;

CREATE TABLE HIGH_CALORIE_MEAL AS SELECT * FROM INGREDIENT WHERE calories > 650;
